disqus = "justinfx"
canonicalurl = "http://justinfx.com"

colorScheme = "fire"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "hybrid"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = true
  showComments = true

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
