baseurl = "http://justinfx.com"
languageCode = "en-us"
title = "JustinFX.com"
disqusShortname = "justinfx"
GoogleAnalytics = "G-0FB13KEJ8V"
copyright = "Justin Israel"
pygmentsstyle = "friendly"

[author]
name = "Justin Israel"

[permalinks]
blog = "/:year/:month/:day/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
canonicalurl = "http://justinfx.com"
description = "Coding, FX, And Just Random Stuff"
author = "Justin Israel"
disqus = "justinfx"
mail = "justinisrael@gmail.com"
github = "https://github.com/justinfx"
linkedin = "https://www.linkedin.com/in/justinisrael/"
facebook = "https://www.facebook.com/justinisrael"
gplus = "https://www.google.com/+JustinIsrael"
youtube = "https://www.youtube.com/c/JustinIsrael"
vimeo = "https://vimeo.com/justinisrael"
stackoverflow = "http://stackoverflow.com/users/496445/jdi"
logo = "/uploads/2009/11/photo1.jpeg"
photo = "/uploads/2009/11/photo1.jpeg"
cover = "/uploads/2014/09/tile2.png"

[[menu.main]]
name = "Developer Resume"
weight = 2
url = "https://stackoverflow.com/cv/justinisrael"

[markup.goldmark.renderer]
unsafe = true
