---
baseurl: "http://justinfx.com"

languageCode: "en-us"
title: "JustinFX.com"
disqusShortname: "justinfx"
copyright: "Justin Israel"
pygmentsstyle: "friendly"

author:
    name: "Justin Israel" 

permalinks:
    blog: :url

taxonomies:
    tag: "tags"
    category: "categories"

params:
    canonicalurl: "http://justinfx.com"
    description: "Coding, FX, And Just Random Stuff"
    author: "Justin Israel"
    disqus: "justinfx"
    mail: "justinisrael@gmail.com"
    github: "https://github.com/justinfx"
    linkedin: "http://www.linkedin.com/in/justinisrael"
    facebook: "https://www.facebook.com/justinisrael"
    gplus: "https://www.google.com/+JustinIsrael"
    vimeo: "http://vimeo.com/justinisrael"
    stackoverflow: "http://stackoverflow.com/users/496445/jdi"
    logo: "/wp-content/uploads/2009/11/photo1.jpeg"
    photo: "/wp-content/uploads/2009/11/photo1.jpeg"
    cover: "/wp-content/uploads/2014/09/tile2.png"
    googleAnalyticsUserID: "UA-6692856-1"
...