---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/page
  label: Page
  create: all
  match: "**/*"
- type: directory
  path: content/wp-content
  label: Wp content
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/public
public_path: "/public"
front_matter_path: "/public"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.42.1
