---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/page
  label: Page
  create: all
  match: "**/*"
- type: directory
  path: content/wp-content
  label: Wp content
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/public
public_path: "/public"
front_matter_path: "/public"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.42.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.42.1
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
version: 0.42.1
